<?php if ($this->isPossibleOnepageCheckout()): ?>
    <a href="<?php echo $this->getCheckoutUrl() ?>" title="<?php echo $this->__('Proceed to checkout') ?>" class="btn btn-success btn-proceed-checkout btn-large pull-right<?php if ($this->isDisabled()): ?> disabled<?php endif; ?>"<?php if ($this->isDisabled()): ?> disabled="disabled"<?php endif; ?>><?php echo $this->__('Proceed to checkout') ?></a>
<?php endif?>
