<div class="block block-progress opc-block-progress">
    <div class="block-title well">
        <h3><?php echo $this->__('Your checkout progress') ?></h3>
    </div>
    <div class="block-content">
        <dl>
            <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
                <?php if ($this->getCheckout()->getStepData('billing', 'complete')): ?>
                    <div class="well">
                        <h3><?php echo $this->__('Billing address') ?></h3> <a href="#billing" onclick="checkout.accordion.openSection('opc-billing'); return false;"><span class="icon-edit"></span> <?php echo $this->__('Change') ?></a>
                        <address><?php echo $this->getBilling()->format('html') ?></address>
                    </div>
                <?php else: ?>
                    <div class="well">
                        <h3><?php echo $this->__('Billing address') ?></h3>
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
                <?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
                    <div class="well">
                        <h3><?php echo $this->__('Shipping address') ?></h3> <a href="#payment" onclick="checkout.accordion.openSection('opc-shipping');return false;"><span class="icon-edit"></span> <?php echo $this->__('Change') ?></a>
                        <address><?php echo $this->getShipping()->format('html') ?></address>
                    </div>
                <?php else: ?>
                    <div class="well">
                        <h3><?php echo $this->__('Shipping address') ?></h3>
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
                <?php if ($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
                    <div class="well">
                        <h3><?php echo $this->__('Shipping method') ?></h3> <a href="#shipping_method" onclick="checkout.accordion.openSection('opc-shipping_method'); return false;"><span class="icon-edit"></span> <?php echo $this->__('Change') ?></a>
                        <?php if ($this->getShippingMethod()): ?>
                            <?php echo $this->getShippingDescription() ?>

                            <?php $_excl = $this->getShippingPriceExclTax(); ?>
                            <?php $_incl = $this->getShippingPriceInclTax(); ?>
                            <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                                <?php echo $_incl; ?>
                            <?php else: ?>
                                <?php echo $_excl; ?>
                            <?php endif; ?>
                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->__('Incl. tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>

                        <?php else: ?>
                            <?php echo $this->__('Shipping method has not been selected yet') ?>
                        <?php endif; ?>
                    </div>
                <?php else: ?>
                    <div class="well">
                        <h3><?php echo $this->__('Shipping method') ?></h3>
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
                <?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
                    <div class="well">
                        <h3><?php echo $this->__('Payment method') ?></h3> <a href="#payment" onclick="checkout.accordion.openSection('opc-payment'); return false;"><span class="icon-edit"></span> <?php echo $this->__('Change') ?></a>
                        <?php echo $this->getPaymentHtml() ?>
                    </div>
                <?php else: ?>
                    <div class="well">
                        <h3><?php echo $this->__('Payment method') ?></h3>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </dl>
    </div>
</div>
