<?php if (!empty($collection) && $collection->getSize()): ?>
    <table class="table table-bordered">
        <col class="span1" />
        <col />
        <tbody>
            <?php foreach ($collection as $_rating): ?>
                <?php if ($_rating->getSummary()): ?>
                    <tr>
                        <th><?php echo $this->__($this->escapeHtml($_rating->getRatingCode())) ?></th>
                        <td>
                            <div class="progress">
                                <div class="bar" style="width:<?php echo ceil($_rating->getSummary()) ?>%;"></div>
                            </div>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
