<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="alert fade in">
        <a class="close" data-dismiss="alert">×</a>
        <?php echo $this->__('There are no products matching the selection.') ?>
    </div>
<?php else: ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list unstyled row-fluid" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?> row-fluid">
                        <div class="span4">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image thumbnail">
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(225); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a>
                        </div>
                        <div class="span8">
                            <div class="thumbnail data">
                                <div class="caption">
                                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                    <h2 class="product-name">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                                    </h2>
                                    <?php if ($_product->getRatingSummary()): ?>
                                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                    <?php endif; ?>
                                    <div class="row-fluid">
                                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <br/>
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><strong><?php echo $this->__('Read more') ?> <i class="icon-share-alt"></i></strong></a>
                                    </div>
                                    <hr/>
                                    <div class="row-fluid">
                                        <div class="span6">
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><span class="icon-heart"></span> <?php echo $this->__('Add to wishlist') ?></a>
                                            <?php endif; ?>
                                            <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                                <span class="separator">&nbsp;</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><span class="icon-list"></span> <?php echo $this->__('Add to compare') ?></a>
                                            <?php endif; ?>
                                        </div>
                                        <div class="span3">
                                            <div class="pull-right">
                                                <strong><?php echo $this->getPriceHtml($_product, true) ?></strong>
                                            </div>
                                        </div>
                                        <div class="span3">
                                            <div class="pull-right">
                                                <?php if ($_product->isSaleable()): ?>
                                                    <a href="<?php echo $this->getAddToCartUrl($_product) ?>" title="<?php echo $this->__('Add to cart') ?>" class="btn btn-small btn-success"><?php echo $this->__('Add to cart') ?></a>
                                                <?php else: ?>
                                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

            <?php // Grid Mode ?>

            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <?php $i = 0;
            foreach ($_productCollection as $_product):
                ?>
                    <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid unstyled thubmnails row-fluid">
            <?php endif ?>
                    <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?> span4">
                        <div class="thumbnail">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image thumbnail"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(225); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

                            <div class="caption">
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                <?php if ($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php endif; ?>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php if ($_product->isSaleable()): ?>
                                    <a href="<?php echo $this->getAddToCartUrl($_product) ?>" title="<?php echo $this->__('Add to cart') ?>" class="btn btn-danger btn-mini"><?php echo $this->__('Add to cart') ?></a>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                <p class="add-to-links unstyled">
                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                        <a href="<?php echo $_compareUrl ?>" class="link-compare pull-right"><span class="icon-list"></span> <?php echo $this->__('Add to compare') ?></a>
                                    <?php endif; ?>
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><span class="icon-heart"></span> <?php echo $this->__('Add to wishlist') ?></a>
            <?php endif; ?>

                                </p>
                            </div>
                        </div>
                    </li>
                <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                    </ul>
                <?php endif ?>
            <?php endforeach ?>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

        <div class="toolbar-bottom">
            <?php
            /* @var $toolbar Mage_Catalog_Block_Product_List_Toolbar */
            // get toolbars limits - overrides default pager limit
            $toolbar = Mage::getBlockSingleton('catalog/product_list_toolbar')->getAvailableLimit();

            /* @var $pager Mage_Page_Block_Html_Pager */
            $pager = $this->getLayout()->createBlock('page/html_pager', 'bootstrapped.standalone.pager');

            // set limit - uses category's instead of default pager's (10-20-50)
            $pager->setAvailableLimit($toolbar);
            // need to set collection
            $pager->setCollection($_productCollection);
            //set custom template
            $pager->setTemplate('catalog/product/list/pager.phtml');
            echo $pager->toHtml();
            ?>
        </div>
    </div>
<?php endif; ?>