<?php if (isset($poll)) : ?>
    <script type="text/javascript">
        //<![CDATA[
        function validatePollAnswerIsSelected()
        {
            var options = $$('input.poll_vote');
            for( i in options ) {
                if( options[i].checked == true ) {
                    return true;
                }
            }
            return false;
        }
        //]]>
    </script>
    <div class="block block-poll well">
        <div class="block-title">
            <h3><?php echo $this->__('Community Poll') ?></h3>
        </div>
        <form id="pollForm" action="<?php echo $action ?>" method="post" onsubmit="return validatePollAnswerIsSelected();" class="form">
            <fieldset>
                <p class="block-subtitle"><?php echo $this->htmlEscape($poll->getPollTitle()); ?></p>
                <?php if ($poll_answers): ?>
                    <?php foreach ($poll_answers as $answer): ?>
                        <div class="poll-answers">


                            <label class="radio" for="vote_<?php echo $answer->getId() ?>">
                                <input type="radio" name="vote" class="radio poll_vote" id="vote_<?php echo $answer->getId() ?>" value="<?php echo $answer->getAnswerId() ?>" />
                                <?php echo $this->htmlEscape($answer->getAnswerTitle()) ?>
                            </label>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <div class="form-actions">
                    <button type="submit" title="<?php echo $this->__('Vote') ?>" class="btn btn-inverse pull-right"><?php echo $this->__('Vote') ?></button>
                </div>
            </fieldset>
        </form>
    </div>
<?php endif; ?>
