<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<p class="my-tag-edit">
    <a href="#" title="<?php echo $this->__('Delete') ?>" onclick="if(confirm('<?php echo $this->__('Are you sure you want to delete this tag?') ?>')) window.location='<?php echo $this->getTagInfo()->getRemoveTagUrl(); ?>'; return false;" class="button btn-remove"><span><?php echo $this->__('Delete') ?></span></a>
    <?php echo $this->__('<strong>Tag name:</strong> <code>%s</code>', $this->htmlEscape($this->getTagInfo()->getName())) ?>
</p>
<div class="clearer"></div>
<?php echo $this->getToolbarHtml() ?>
<table class="table table-striped table-bordered table-condensed" id="my-tags-table">
<?php if( sizeof($this->getMyProducts()) > 0 ): ?>
    <tbody>
    <?php foreach($this->getMyProducts() as $_product): ?>
        <tr>
            <td class="">
                <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(100, 100); ?>" width="100" height="100" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
            </td>
            <td>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php echo $this->getPriceHtml($_product) ?>
                <?php echo $this->htmlEscape($_product->getDescription()) ?>
            </td>
            <td class="">
                <?php if($_product->isSaleable()): ?>
                    <a title="<?php echo $this->__('Add to cart') ?>" class="btn btn-success" href="<?php echo $this->getUrl('checkout/cart/add',array('product'=>$_product->getId())) ?>"><?php echo $this->__('Add to cart') ?></a>
                <?php endif; ?>
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $this->getUrl('wishlist/index/add',array('product'=>$_product->getId())) ?>"><?php echo $this->__('Add to wishlist') ?></a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
<?php else: ?>
    <tbody>
        <tr>
            <td>
                <?php echo $this->__("Unable to find any products tagged with '%s' in the current store", $this->htmlEscape($this->getTagInfo()->getName()) ) ?>
            </td>
        </tr>
    </tbody>
<?php endif; ?>
</table>
<?php echo $this->getToolbarHtml() ?>