<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">
    <div class="row-fluid">
        <?php if (!$this->hasError()): ?>
            <?php foreach ($this->getMethods('top_methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                    <?php echo $methodHtml; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <div class="row-fluid">
        <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
            <fieldset>
                <table id="shopping-cart-table" class="data-table cart-table table table-striped table-bordered table-condensed table-white">
                    <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                    <thead>
                        <tr>
                            <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                            <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product name') ?></span></th>
                            <th rowspan="<?php echo $mergedCells; ?>"></th>
                            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                                <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to wishlist') ?></span></th>
                            <?php endif ?>
                            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit price') ?></span></th>
                            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
                            <th rowspan="<?php echo $mergedCells; ?>" class="a-center">&nbsp;</th>
                        </tr>
                        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                            <tr>
                                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                            </tr>
                        <?php endif; ?>
                    </thead>
                    <tbody>
                        <?php foreach ($this->getItems() as $_item): ?>
                            <?php echo $this->getItemHtml($_item) ?>
                        <?php endforeach ?>
                    </tbody>
                </table>
                <?php if ($this->getContinueShoppingUrl()): ?>
                    <a title="<?php echo $this->__('Continue shopping') ?>" class="btn" href="<?php echo $this->getContinueShoppingUrl() ?>"><?php echo $this->__('Continue shopping') ?></a>
                <?php endif; ?>
                <button type="submit" title="<?php echo $this->__('Update shopping cart') ?>" class="btn pull-right"><?php echo $this->__('Update shopping cart') ?></button>
            </fieldset>
        </form>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <div class="well">
                <?php echo $this->getChildHtml('coupon') ?>
            </div>
            <div class="well">
                <?php if (!$this->getIsVirtual()): ?>
                    <?php echo $this->getChildHtml('shipping'); ?>
                <?php endif; ?>
            </div>
        </div>
        <div class="span6">
            <div class="well">
                <?php echo $this->getChildHtml('totals'); ?>
                <div class="form-actions">
                    <?php if (!$this->hasError()): ?>
                        <?php foreach ($this->getMethods('methods') as $method): ?>
                            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                                <?php echo $methodHtml; ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
            <?php echo $this->getChildHtml('crosssell') ?>
        </div>
    </div>
</div>
