<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<div class="opc" id="checkoutSteps">
    <?php $i = 0; ?>
    <?php foreach ($this->getSteps() as $_stepId => $_stepInfo): ?>
        <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): ?>
            <?php continue; ?>
        <?php endif; ?>
        <?php $i++ ?>
        <div id="opc-<?php echo $_stepId ?>" class="section<?php echo!empty($_stepInfo['allow']) ? ' allow' : '' ?><?php echo!empty($_stepInfo['complete']) ? ' saved' : '' ?>">
            <div class="<?php if ('login' !== $_stepId) : ?>well<?php endif ?>">
                <div class="step-title">
                    <a class="pull-right" href="#"><span class="icon-edit"></span> <?php echo $this->__('Edit') ?></a>
                    <h3><?php echo $_stepInfo['label'] ?></h3>
                </div>
                <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
                    <?php echo $this->getChildHtml($_stepId) ?>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>
<script type="text/javascript">
//<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
<?php if ($this->getActiveStep()): ?>
                        accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
<?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>
