<div class="container">
    <div class="info-footer">
        <div class="row-fluid">
            <div class="span3">
                <h3>Oz Publishing</h3>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_contact_details')->toHtml() ?>
            </div>
            <div class="span3">
                <h3>&nbsp;</h3>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cms_footer_links')->toHtml() ?>
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml() ?>
            </div>
            <div class="span6">
                <h3>&nbsp;</h3>
                <?php echo $this->getChildHtml() ?>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="copyright-footer">
            <div class="span2">
                <div class="logo">
                    <a href="<?php echo $this->getUrl('') ?>">
                        <img src="<?php echo $this->getSkinUrl('img/logo-white.png') ?>" alt="<?php echo Mage::getStoreConfig('design/header/logo_alt') ?>"/>
                    </a>
                </div>
            </div>
            <div class="span10">
                <div class="copyright">
                    <p><?php echo $this->getCopyright() ?></p>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <?php echo $this->getLayout()->createBlock('page/html')->getAbsoluteFooter()?>
    </div>
</div>