<div class="container">
    <div class="row-fluid">
        <div class="span6 logo">
            <a href="<?php echo $this->getUrl('') ?>">
                <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>"/>
            </a>
        </div>
        <div class="span6 social-links hidden-phone">
            <ul class="pull-right">
                <li><a href="#"><i class="fa-icon-facebook"></i></a></li>
                <li><a href="#"><i class="fa-icon-github"></i></a></li>
                <li><a href="#"><i class="fa-icon-pinterest"></i></a></li>
                <li><a href="https://twitter.com/OzPublishingAU"><i class="fa-icon-twitter"></i></a></li>
                <li><a href="#"><i class="fa-icon-envelope-alt"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="row-fluid">
        <div class="navigation">
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="nav-collapse collapse">
                        <?php echo $this->getChildHtml('topLinks') ?>
                        <?php echo $this->getChildHtml('topSearch') ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
