<div class="container">
    <div class="row-fluid">
        <div class="span2 logo">
            <a href="<?php echo $this->getUrl('') ?>">
                <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>"/>
            </a>
        </div>
        <div class="span3">
            <a href="<?php echo $this->getUrl('big-books') ?>">
                <img src="<?php echo $this->getSkinUrl('img/big-books-heading.png') ?>" alt="<?php echo $this->__('Big Boks') ?>" class="v-middle"/>
            </a>
        </div>
        <div class="span1"></div>
        <div class="span6 social-links hidden-phone">
            <div class="pull-right">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('header_social_links')->toHtml() ?>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="navigation">
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="nav-collapse collapse">
                        <?php echo $this->getChildHtml('top.links') ?>
                        <?php echo $this->getChildHtml('topLinks') ?>
                        <?php echo $this->getChildHtml('topSearch') ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
