<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="">    
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getSkinUrl('img/favicon.ico') ?>" type="image/x-icon" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->getSkinUrl('img/logo-114x114-bw.png') ?>"/>
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->getSkinUrl('img/logo-72x72-bw.png') ?>"/>
<link rel="apple-touch-icon-precomposed" href="<?php echo $this->getSkinUrl('img/logo-57x57-bw.png') ?>"/>
<link rel="apple-touch-icon" href="<?php echo $this->getSkinUrl('img/logo-114x114-bw.png') ?>"/>

<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Droid+Sans:400,700">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Droid+Serif">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Boogaloo">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Economica:700,400italic">

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

