<?php
/**
 * One page checkout payment methods
 *
 * @see Mage_Checkout_Block_Onepage_Payment_Methods
 */
?>
<div id="checkout-payment-method-load">
    <?php
    $methods = $this->getMethods();
    $oneMethod = count($methods) <= 1;
    ?>
    <?php
    foreach ($methods as $_method):
        $_code = $_method->getCode();
        ?>
        <div class="control-group">
            <div class="controls">
                <label class="radio">
                    <?php if (!$oneMethod): ?>
                        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if ($this->getSelectedMethodCode() == $_code): ?> checked="checked"<?php endif; ?> class="radio" />
                    <?php else: ?>
                        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
                            <?php $oneMethod = $_code; ?>
                        <?php endif; ?>
                        <?php echo $this->getMethodTitle($_method) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?>
                </label>
                <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
                    <div>
                        <?php echo $html; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
    //<![CDATA[
<?php echo $this->getChildChildHtml('scripts'); ?>
    payment.init();
<?php if (is_string($oneMethod)): ?>
        payment.switchMethod('<?php echo $oneMethod ?>');
<?php endif; ?>
    //]]>
</script>
