<div class="control-group">
    <label for="<?php echo $this->getFieldId('taxvat') ?>" class="control-label<?php if ($this->isRequired()) echo ' required' ?>"><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->__('Tax/VAT number') ?></label>
    <div class="controls">
        <input type="text" id="<?php echo $this->getFieldId('taxvat') ?>" name="<?php echo $this->getFieldName('taxvat') ?>" value="<?php echo $this->htmlEscape($this->getTaxvat()) ?>" title="<?php echo $this->__('Tax/VAT number') ?>" class="input-text<?php if ($this->isRequired()): ?> required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?> />
    </div>
</div>
