<div class="nav-container well sidebar-nav">
    <ul class="nav nav-list">
        <?php $_links = $this->getLinks(); ?>
        <?php $_index = 1; ?>
        <?php $_count = count($_links); ?>
        <?php foreach ($_links as $_link): ?>
            <?php if ($this->isActive($_link)): ?>
                <li class="active" <?php echo $_link->getLiParams() ?>>
                    <a href="<?php echo $_link->getUrl() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a>
                </li>
            <?php else: ?>
                <li <?php echo $_link->getLiParams() ?>>
                    <a href="<?php echo $_link->getUrl() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div>
