<?php $_helper = $this->helper('catalog/output'); ?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="widget widget-new-products">
        <div class="widget-title">
            <h2><?php echo $this->__('New products') ?></h2>
        </div>
        <hr class="clean"/>
        <div class="widget-products">
            <ol class="products-list">
                <?php $i = 0; ?>
                <?php foreach ($_products->getItems() as $_product): ?>
                    <li class="row-fluid item<?php echo (++$i == count($_products)) ? ' last' : ''; ?>">
                        <div class="span4">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image thumbnail">
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(225); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a>
                        </div>
                        <div class="span8">
                            <div class="thumbnail data">
                                <div class="caption">
                                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                    <h2 class="product-name">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                                    </h2>
                                    <?php if ($_product->getRatingSummary()): ?>
                                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                    <?php endif; ?>
                                    <div class="row-fluid">
                                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <br/>
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><strong><?php echo $this->__('Read more') ?> <i class="icon-share-alt"></i></strong></a>
                                    </div>
                                    <hr/>
                                    <div class="row-fluid">
                                        <div class="span6">
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><span class="icon-heart"></span> <?php echo $this->__('Add to wishlist') ?></a>
                                            <?php endif; ?>
                                            <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                                <span class="separator">&nbsp;</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><span class="icon-list"></span> <?php echo $this->__('Add to compare') ?></a>
                                            <?php endif; ?>
                                        </div>
                                        <div class="span3">
                                            <div class="pull-right">
                                                <strong><?php echo $this->getPriceHtml($_product, true, '-widget-new-list') ?></strong>
                                            </div>
                                        </div>
                                        <div class="span3">
                                            <div class="pull-right">
                                                <?php if ($_product->isSaleable()): ?>
                                                    <a href="<?php echo $this->getAddToCartUrl($_product) ?>" title="<?php echo $this->__('Add to cart') ?>" class="btn btn-small btn-success"><?php echo $this->__('Add to cart') ?></a>
                                                <?php else: ?>
                                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>
