<div class="page-header">
    <h1><?php echo $this->__('All tags') ?></h1>
</div>
<?php if( sizeof($this->getTags()) > 0 ): ?>
    <p class="tags-list">
        <?php foreach ($this->getTags() as $_tag): ?>
            <a href="<?php echo $_tag->getTaggedProductsUrl() ?>"><span class="label" style="font-size:<?php echo $_tag->getRatio()*70+85 ?>%;"><?php echo $this->htmlEscape($_tag->getName()) ?></span></a>
        <?php endforeach; ?>
    </p>
<?php else: ?>
    <p class="note-msg"><?php echo $this->__('There are no tags available.') ?></p>
<?php endif; ?>
