<div class="box-collateral box-tags">
    <?php echo $this->getChildHtml('list_before')?>
    <?php if( $this->getCount() ): ?>
    <p><?php echo $this->__('Other people marked this product with these tags:') ?></p>
    <ul id="<?php echo $this->getUniqueHtmlId('product-tags_'); ?>" class="product-tags">
        <?php echo $this->renderTags('<li><a href="%1$s"><span class="label">%2$s (%3$s)</span></a></li>') ?>
    </ul>
    <?php endif; ?>
    <form id="addTagForm" action="<?php echo $this->getFormAction(); ?>" method="get" class="form-inline">
        <label for="productTagName"><?php echo $this->__('Add your tags') ?></label>
        <input type="text" class="required-entry" name="productTagName" id="productTagName" />
        <button type="button" title="<?php echo $this->__('Add tags') ?>" class="btn" onclick="submitTagForm()">
            <?php echo $this->__('Add tags') ?>
        </button>
    </form>
    <p class="help-block"><?php echo $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
    <script type="text/javascript">
    //<![CDATA[
        var addTagFormJs = new VarienForm('addTagForm');
        function submitTagForm(){
            if(addTagFormJs.validator.validate()) {
                addTagFormJs.form.submit();
            }
        }
    //]]>
    </script>
</div>
