<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="add-to-cart form-inline form-actions">
        <?php if (!$_product->isGrouped()): ?>
            <label for="qty" class="control-label"><?php echo $this->__('Qty:') ?></label>
            <input type="number" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="qty input-small" />
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="btn btn-success" onclick="productAddToCartForm.submit(this)"><?php echo $buttonTitle ?></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
