<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <p>
        <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, '<?php echo $_wishlistSubmitUrl ?>'); return false;" class="link-wishlist"><span class="icon-heart"></span> <?php echo $this->__('Add to wishlist') ?></a>
    </p>
<?php endif; ?>
<?php
$_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
?>
<?php if ($_compareUrl) : ?>
    <p>
        <a href="<?php echo $_compareUrl ?>" class="link-compare"><span class="icon-list"></span> <?php echo $this->__('Add to compare') ?></a>
    </p>
<?php endif; ?>
