<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct()
?>
<?php if ($_additional = $this->getAdditionalData()): ?>
    <?php foreach ($_additional as $_data): ?>
        <div class="row-fluid product-attribute">
            <div class="span4">
                <strong><?php echo $this->htmlEscape($this->__($_data['label'])) ?></strong>
            </div>
            <div class="span8">
                <?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
            </div>
        </div>
        <hr/>
    <?php endforeach; ?>
<?php endif; ?>
