<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<ul class="nav nav-tabs">
    <?php foreach ($this->getTabs() as $_index => $_tab): ?>
        <?php if ($this->getChildHtml($_tab['alias'])): ?>
            <li class="<?php echo!$_index ? 'active' : '' ?>"><a data-toggle="tab" href="#product_tabs_<?php echo str_replace('.', '_', $_tab['alias']) ?>"><?php echo $_tab['title'] ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<div class="tab-content">
    <?php foreach ($this->getTabs() as $_index => $_tab): ?>
        <?php if ($this->getChildHtml($_tab['alias'])): ?>
            <div class="tab-pane fade <?php echo!$_index ? ' in active' : '' ?>" id="product_tabs_<?php echo str_replace('.', '_', $_tab['alias']) ?>">
                <?php echo $this->getChildHtml($_tab['alias']) ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
