<?php
$_categories = $this->getRssCatalogFeeds();
$_misc = $this->getRssMiscFeeds();
?>
<?php if ($_categories || $_misc): ?>
    <?php if ($_misc): ?>
        <table class="table table-bordered table-striped table-white">
            <colgroup>
                <col class="span10"/>
                <col class="span2" />
            </colgroup>
            <thead>
                <tr>
                    <th colspan="2"><?php echo $this->__('Miscellaneous feeds') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_misc as $_feed): ?>
                    <tr>
                        <td><?php echo $_feed->getLabel() ?></td>
                        <td><a href="<?php echo $_feed->getUrl() ?>" class="link-rss"><i class="fa-icon-rss"></i> <?php echo $this->__('Get feed'); ?></a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
    <?php if ($_categories && $_misc): ?>
        <br />
    <?php endif ?>
    <?php if ($_categories): ?>
        <table class="table table-bordered table-striped table-white">
            <colgroup>
                <col class="span10"/>
                <col class="span2" />
            </colgroup>
            <thead>
                <tr>
                    <th colspan="2"><?php echo $this->__('Category feeds') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_categories as $_category): ?>
                    <tr>
                        <td><?php echo $_category->getLabel() ?></td>
                        <td><a href="<?php echo $_category->getUrl() ?>" class="link-rss"><i class="fa-icon-rss"></i> <?php echo $this->__('Get feed'); ?></a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php else: ?>
    <p><?php echo $this->__('There are no RSS feeds.'); ?></p>
<?php endif; ?>
