<?php
/* @var $this Mage_Catalog_Block_Product_Compare_List */
?>
<?php $_total = $this->getItems()->getSize() ?>
<?php if ($_total): ?>
    <table class="data-table compare-table table table-bordered table-striped table-condensed table-white" id="product_comparison">
        <?php $_i = 0 ?>
        <?php foreach ($this->getItems() as $_item): ?>
            <?php if ($_i++ % 10 == 0): ?>
                <col width="1" />
            <?php endif; ?>
            <col width="<?php echo floor(100 / $_total); ?>%" />
        <?php endforeach; ?>
        <?php if ($_total > 2): ?>
            <thead>
                <tr>
                    <?php $_i = 0 ?>
                    <?php foreach ($this->getItems() as $_item): ?>
                        <?php if ($_i++ % 10 == 0): ?>
                            <th>&nbsp;</th>
                        <?php endif; ?>
                        <td class="a-right">
                            <a href="#" class="btn-remove" onclick="removeItem('<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>');" title="<?php echo $this->__('Remove this item') ?>"><span class="icon-remove"></span> <?php echo $this->__('Remove this item') ?></a>
                        </td>
                    <?php endforeach; ?>
                </tr>
            </thead>
        <?php endif ?>
        <tbody>
            <tr class="product-shop-row">
                <?php $_i = 0 ?>
                <?php foreach ($this->getItems() as $_item): ?>
                    <?php if ($_i++ % 10 == 0): ?>
                        <th>&nbsp;</th>
                    <?php endif; ?>
                    <td>
                        <p class="product-name">
                            <a href="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
                                <strong><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></strong>
                            </a>
                        </p>
                        <a class="product-image" href="#" onclick="setPLocation('<?php echo $this->getProductUrl($_item) ?>', true)" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125, 125); ?>" width="125" height="125" alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" /></a>
                        <?php echo $this->getReviewsSummaryHtml($_item, 'short') ?>
                        <?php echo $this->getPriceHtml($_item, true, '-compare-list-top') ?>
                        <?php if ($_item->isSaleable()): ?>
                            <a title="<?php echo $this->__('Add to cart') ?>" class="btn btn-small btn-success" href="<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item) ?>"><?php echo $this->__('Add to cart') ?></a>
                        <?php else: ?>
                            <span class="label label-danger"><?php echo $this->__('Out of stock') ?></span>
                        <?php endif; ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="btn btn-small"><?php echo $this->__('Add to wishlist') ?></a>
                        <?php endif; ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        </tbody>
        <tbody>
            <?php foreach ($this->getAttributes() as $_attribute): ?>
                <tr>
                    <?php $_i = 0 ?>
                    <?php foreach ($this->getItems() as $_item): ?>
                        <?php if ($_i++ % 10 == 0): ?>
                            <th><span class="nobr"><?php echo $_attribute->getStoreLabel() ?></span></th>
                        <?php endif; ?>
                        <td>
                            <?php
                            switch ($_attribute->getAttributeCode()) {
                                case "price":
                                    ?>
                                    <?php echo $this->getPriceHtml($_item, true, '-compare-list-' . $_attribute->getCode()) ?>
                                    <?php
                                    break;
                                case "small_image":
                                    ?>
                                    <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125, 125); ?>" width="125" height="125" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" />
                                    <?php
                                    break;
                                case "date":
                                    echo substr($this->getProductAttributeValue($_item, $_attribute), 0, 10);
                                    break;
                                default:
                                    ?>
                                    <div class="std">
                                        <?php echo $this->helper('catalog/output')->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
                                    </div>
                                    <?php
                                    break;
                            }
                            ?>
                        </td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tbody>
            <tr class="add-to-row">
                <?php $_i = 0 ?>
                <?php foreach ($this->getItems() as $_item): ?>
                    <?php if ($_i++ % 10 == 0): ?>
                        <th>&nbsp;</th>
                    <?php endif; ?>
                    <td>
                        <?php echo $this->getPriceHtml($_item, true, '-compare-list-bottom') ?>
                        <?php if ($_item->isSaleable()): ?>
                            <a title="<?php echo $this->__('Add to cart') ?>" class="btn btn-small btn-success" href="<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item) ?>"><?php echo $this->__('Add to cart') ?></a>
                        <?php else: ?>
                            <span class="label label-danger"><?php echo $this->__('Out of stock') ?></span>
                        <?php endif ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="btn btn-small"><?php echo $this->__('Add to wishlist') ?></a>
                        <?php endif ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        </tbody>
    </table>
    <script type="text/javascript">
        decorateTable('product_comparison');

        /**
         * Send remove item request, after that reload windows
         */
        function removeItem(url)
        {
            new Ajax.Request(url, {
                parameters: {isAjax: 1, method: 'POST'},
                onLoading: function(){$('compare-list-please-wait').show();},
                onSuccess: function(transport) {
                    $('compare-list-please-wait').hide();
                    window.location.reload();
                    window.opener.location.reload();
                }
            });
        }
    </script>
<?php else: ?>
    <script type="text/javascript">window.close();</script>
<?php endif; ?>
