<?php /* @var $this Mage_Catalog_Block_Product_Compare_Sidebar */ ?>
<?php
$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
?>
<div class="block block-list block-compare well">
    <div class="block-title">
        <h3>
            <?php echo $this->__('Compare products') ?>
            <?php if ($_helper->getItemCount() > 0): ?> 
                <small><?php echo $this->__('(%d)', $_helper->getItemCount()) ?></small>
            <?php endif; ?>
        </h3>
    </div>
    <div class="block-content">
        <?php if ($_helper->getItemCount() > 0): ?>
            <?php foreach ($_items as $_index => $_item): ?>
                <div class="item">
                    <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
                    <div class="modal hide fade" id="compare_<?php echo $this->escapeHtml($_item->getId()) ?>" style="display: none;">
                        <div class="modal-header">
                            <a class="close" data-dismiss="modal">×</a>
                            <h3>Remove item</h3>
                        </div>
                        <div class="modal-body">
                            <p><?php echo $this->__(sprintf('Are you sure you would like to remove <strong>%s</strong> from the compare products list?', $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name'))) ?></p>
                        </div>
                        <div class="modal-footer">
                            <a href="<?php echo $_helper->getRemoveUrl($_item) ?>" class="btn btn-success"><?php echo $this->__('Remove') ?></a>
                            <a href="#" class="btn" data-dismiss="modal"><?php echo $this->__('Cancel') ?></a>
                        </div>
                    </div>
                    <a class="pull-right" data-toggle="modal" href="#compare_<?php echo $this->escapeHtml($_item->getId()) ?>" title="<?php echo $this->__('Remove this item') ?>" ><span class="icon-remove"></span></a>
                    <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
                </div>
            <?php endforeach; ?>
            <a href="<?php echo $_helper->getListUrl() ?>" title="<?php echo $this->__('Compare') ?>" class="btn btn-success"><?php echo $this->__('Compare') ?></a>
            <a class="btn" data-toggle="modal" href="#delete_items_modal"><?php echo $this->__('Clear all') ?></a>
        <?php else: ?>
            <p class="empty"><?php echo $this->__('You have no items to compare.') ?></p>
        <?php endif; ?>
    </div>
</div>
<div class="modal hide fade" id="delete_items_modal" style="display: none;">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>Clear all</h3>
    </div>
    <div class="modal-body">
        <p><?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?></p>
    </div>
    <div class="modal-footer">
        <a href="<?php echo $_helper->getClearListUrl() ?>" class="btn btn-success"><?php echo $this->__('Clear all') ?></a>
        <a href="#" class="btn" data-dismiss="modal"><?php echo $this->__('Cancel') ?></a>
    </div>
</div>