<?php /* @var $this Mage_Core_Block_Captcha_Zend */ ?>

<?php /* @var $captcha Mage_Core_Model_Captcha_Zend */ ?>
<?php $captcha = $this->getCaptchaModel() ?>
<div class="control-group" id="captcha-input-box-<?php echo $this->getFormId()?>">

    <?php /*?><label for="captcha_<?php echo $this->getFormId() ?>" class="required control-label"><em>*</em><?php echo $this->__('Please type the letters below')?></label><?php */?>
    <div class="controls input-box captcha">
        <input name="<?php echo Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?php echo $this->getFormId()?>]" type="text" class="input-text required-entry" id="captcha_<?php echo $this->getFormId() ?>" />
        <span class="help-block"><em>*</em><?php echo $this->__('Please type the letters below')?></span>
    </div>
</div>
<div class="control-group">
    <div class="controls captcha-image" id="captcha-image-box-<?php echo $this->getFormId()?>">
        <img id="captcha-reload" class="captcha-reload" src="<?php echo $this->getSkinUrl('images/reload.png') ?>" alt="<?php echo $this->__('Reload captcha') ?>" onclick="$('<?php echo $this->getFormId()?>').captcha.refresh(this)">
        <img id="<?php echo $this->getFormId() ?>" class="captcha-img" height="<?php echo $this->getImgHeight() ?>" src="<?php echo $captcha->getImgSrc() ?>"/>
        <?php if ($captcha->isCaseSensitive()) :?>
        <div class="captcha-note">
            <?php echo $this->__('<strong>Attention</strong>: Captcha is case sensitive.') ?>
        </div>
        <?php endif; ?>
    </div>
    <script type="text/javascript">//<![CDATA[
        $('<?php echo $this->getFormId() ?>').captcha = new Captcha('<?php echo $this->getRefreshUrl() ?>', '<?php echo $this->getFormId() ?>');
    //]]></script>
</div>

