<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
    <head>
        <?php echo $this->getChildHtml('head') ?>
    </head>
    <body<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : '' ?>>
        <?php echo $this->getChildHtml('after_body_start') ?>
        <header>
            <?php echo $this->getChildHtml('header') ?>
        </header>
        <div class="container">
            <div class="row-fluid">
                <div class="main-container">
                    <div class="page-header clearfix">
                        <div class="pull-left">
                            <?php echo $this->getChildHtml('page_header') ?>
                        </div>
                        <div class="pull-right">
                            <?php echo $this->getChildHtml('breadcrumbs') ?>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span3">
                            <?php echo $this->getChildHtml('left') ?>
                        </div>
                        <div class="span9">
                            <?php echo $this->getChildHtml('global_messages') ?>
                            <?php echo $this->getChildHtml('content') ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer>
            <?php echo $this->getChildHtml('footer') ?>
            <?php echo $this->getChildHtml('global_notices') ?>
        </footer>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </body>
</html>
