<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
    <head>
        <?php echo $this->getChildHtml('head') ?>
    </head>
    <body class="page-popup<?php echo $this->getBodyClass() ? $this->getBodyClass() : '' ?>">
        <div>
            <?php echo $this->getChildHtml('after_body_start') ?>
            <?php echo $this->getChildHtml('content') ?>
        </div>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </body>
</html>
