<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="row-fluid">
    <div class="span6">
        <div class="well">
            <h2><?php echo $this->__('New customers') ?></h2>
            <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
            <hr/>
            <a href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>" title="<?php echo $this->__('Create an account') ?>" class="button btn btn-large btn-success"><?php echo $this->__('Create an account') ?></a>
        </div>
    </div>
    <div class="span6">
        <div class="well">
            <h2><?php echo $this->__('Registered customers') ?></h2>
            <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
            <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form"  class="form-vertical">
                <div class="control-group">
                    <label class="control-label required" for="email"><?php echo $this->__('Email address') ?></label>
                    <div class="controls">
                        <input name="login[username]" id="email" title="<?php echo $this->__('Email address') ?>" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" class="input-xlarge required-entry validate-email" type="email" />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label required" for="pass"><?php echo $this->__('Password') ?></label>
                    <div class="controls">
                        <input name="login[password]" id="pass" title="<?php echo $this->__('Password') ?>" class="input-xlarge required-entry validate-password" type="password" />
                    </div>
                </div>
                <div class="control-group">
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                </div>
                <hr/>
                <div>
                    <button type="submit" class="btn btn-large" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><?php echo $this->__('Login') ?></button>
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="pull-right"><?php echo $this->__('Forgot your password?') ?></a>
                </div>
                <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                    <input name="context" type="hidden" value="checkout" />
                <?php endif; ?>

                <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                    <input name="context" type="hidden" value="checkout" />
                <?php endif; ?>
            </form>
        </div>
    </div>
</div>
