<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2><?php echo $this->__('Retrieve your password here.') ?></h2>
<p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <div class="control-group">
        <label class="control-label required" for="email_address"><?php echo $this->__('Email address') ?></label>
        <div class="controls">
            <input name="email" id="email_address" title="<?php echo $this->__('Email address') ?>" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" class="span4 focused required-entry validate-email" type="email"/>
        </div>
    </div>
    <hr/>
    <div class="form-actions">
        <button type="submit" class="btn btn-large"  title="<?php echo $this->__('Send') ?>"><?php echo $this->__('Send') ?></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
