<div class="page-header">
    <h1><?php echo $this->__('Newsletter subscription') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<div class="hero-unit">
    <h2><?php echo $this->__('Sign up to our newsletter so that you receive special offers plus more.') ?></h2>
    <form action="<?php echo $this->getAction() ?>" method="post" id="form-validate" class="form-horizontal">
        <fieldset>
            <legend><?php echo $this->__('You are subscribed to these newsletters.') ?></legend>
            <div class="control-group">
                <label class="control-label" for="subscription"><?php echo $this->__('General subscription') ?></label>
                <div class="controls">
                    <label class="checkbox">
                        <input type="checkbox" value="1" id="subscription" name="is_subscribed" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> />
                    </label>
                </div>
            </div>
            <?php echo $this->getBlockHtml('formkey')?>
        </fieldest>
        <div class="form-actions">
            <button type="submit" title="<?php echo $this->__('Save') ?>" class="btn btn-large"><?php echo $this->__('Save') ?></button>
        </div>
    </form>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
