<div class="block block-subscribe well">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="control-group">
            <label for="newsletter" class="control-label"><?php echo $this->__('Sign up for our email newsletter') ?></label>
            <div class="controls">
                <div class="input-prepend input-append">
                    <span class="add-on"><i class="icon-envelope"></i></span>
                    <input type="email" name="email" id="newsletter" class="span8" required="required" placeholder="<?php echo $this->helper('newsletter')->__('Enter your email') ?>"/><button type="submit" class="btn btn-inverse"><?php echo $this->__('Go') ?></button>
                </div>
            </div>
        </div>
        <script type="text/javascript">
        //<![CDATA[
            var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
        //]]>
        </script>
    </form>
</div>