<h2><?php echo $this->__('New customers') ?></h2>
<p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
<hr/>
<a href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>" title="<?php echo $this->__('Create an account') ?>" class="button btn btn-large btn-success"><?php echo $this->__('Create an account') ?></a>
