<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
<ul class="links nav"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
    <?php foreach($_links as $_link): ?>
        <?php $liClasses = array() ?>
        
        <?php if ($_link->getIsFirst()): ?>
            <?php $liClasses[] = 'first' ?>
        <?php endif ?>

        <?php if ($_link->getIsLast()): ?>
            <?php $liClasses[] = 'last' ?>
        <?php endif ?>
        
        <?php if (($currentUrl = trim(Mage::helper('core/url')->getCurrentUrl(), '/')) === ($linkUrl = trim($_link->getUrl(), '/'))): ?>
            <?php $liClasses[] = 'active' ?>
        <?php endif ?>
    
        <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
            <?php echo $_link->toHtml() ?>
        <?php else: ?>
            <li class="<?php echo implode(' ', $liClasses) ?>" <?php echo $_link->getLiParams() ?>>
                <?php echo $_link->getBeforeText() ?>
                <a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a>
                <?php echo $_link->getAfterText() ?>
            </li>
        <?php endif;?>
    <?php endforeach; ?>            
    <?php echo $this->getChildHtml('store_language') ?>
</ul>
<?php endif; ?>
