<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
    <div class="block block-list block-compared well">
        <div class="block-title">
            <h3><?php echo $this->__('Recently compared products') ?></h3>
        </div>
        <div class="block-content">
            <?php foreach ($_products as $_item): ?>
                <div class="item">
                    <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
