<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
    <div class="block block-list block-viewed well">
        <div class="block-title">
            <h3><?php echo $this->__('Recently viewed products') ?></h3>
        </div>
        <div class="block-content">
            <?php foreach ($_products as $_item): ?>
                <div class="item">
                    <p class="">
                        <a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a>
                    </p>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
