<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>
<div class="block nav-container well sidebar-nav">
    <ul class="nav nav-list">
        <li class="nav-header"><?php echo $this->__('Browse By') ?> <?php echo $this->__('Category') ?></li>
        <?php echo $_menu ?>
    </ul>
</div>
<?php endif ?>
