<?php
/* @var $this Mage_Sendfriend_Block_Send */
/**
 * Send to friend form
 *
 * @see Mage_Sendfriend_Block_Send
 */
?>
<script type="text/javascript">
    //<![CDATA[
    i=0;
    var recipCount  = 1;
    var maxRecip    = <?php echo $this->getMaxRecipients() ?>;
    function remove_recipient(i){
        $('recipients_name'+i).up(2).remove();
        recipCount--;
        if(recipCount<maxRecip && maxRecip != 0) {
            $('add_recipient_button').show();
            $('max_recipient_message').hide();
        }
        return false;
    }

    function add_recipient(){
        ul = $('recipients_options');
        var li_mail = Element.extend(document.createElement("DIV"));
        li_mail.addClassName('fields additional-row');
        li_mail.innerHTML = '<p><a href="delete_email" title="<?php echo $this->__('Remove email') ?>" onclick="remove_recipient('+i+'); return false" class="btn-remove"><span class="icon-remove"></span><\/a><\/p>'
        li_mail.innerHTML += '<div class="field"><label for="recipients_name'+i+'" class="control-label required"><?php echo $this->__('Name') ?><\/label><div class="controls"><input name="recipients[name][]" type="text" class="span12 required-entry" id="recipients_name'+i+'" /><\/div>';
        li_mail.innerHTML += '<div class="field"><label for="recipients_email'+i+'" class="control-label required"><?php echo $this->__('Email address') ?><\/label><div class="controls"><input name="recipients[email][]" value="" title="<?php echo $this->__('Email address') ?>" id="recipients_email'+i+'" type="text" class="span12 required-entry validate-email" /><\/div><\/div>';
        i++;
        recipCount++;
        if(recipCount>=maxRecip && maxRecip != 0) {
            $('add_recipient_button').hide();
            $('max_recipient_message').show();
        }

        ul.appendChild(li_mail);
    }
    //]]>
</script>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSendUrl() ?>" method="post" id="product_sendtofriend_form">
    <div class="row-fluid">
        <div class="span12">
            <div class="row-fluid">
                <div class="span6">
                    <fieldset>
                        <?php echo $this->getBlockHtml('formkey') ?>
                        <legend><?php echo $this->__('Sender') ?></legend>
                        <div id="sender_options">
                            <div class="control-group">
                                <label for="sender_name" class="control-label required"><?php echo $this->__('Name') ?></label>
                                <div class="controls">
                                    <input name="sender[name]" value="<?php echo $this->htmlEscape($this->getUserName()) ?>" title="<?php echo $this->__('Name') ?>" id="sender_name" type="text" class="span12 required-entry" />
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="sender_email" class="control-label required"><?php echo $this->__('Email') ?></label>
                                <div class="controls">
                                    <input name="sender[email]" value="<?php echo $this->htmlEscape($this->getEmail()) ?>" title="<?php echo $this->__('Email address') ?>" id="sender_email" type="text" class="span12 required-entry validate-email" />
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="sender_message" class="control-label required"><?php echo $this->__('Message') ?></label>
                                <div class="controls">
                                    <textarea name="sender[message]" class="span12 required-entry" id="sender_message" cols="3" rows="3"><?php echo $this->htmlEscape($this->getMessage()) ?></textarea>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="span6">
                    <fieldset>
                        <legend><?php echo $this->__('Recipient') ?></legend>
                        <div id="recipients_options">
                            <div class="control-group">
                                <label for="recipients_name" class="control-label required"><?php echo $this->__('Name') ?></label>
                                <div class="controls">
                                    <input name="recipients[name][]" type="text" class="span12 required-entry" id="recipients_name" />
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="recipients_email" class="control-label required"><?php echo $this->__('Email address') ?></label>
                                <div class="controls">
                                    <input name="recipients[email][]" value="" title="<?php echo $this->__('Email address') ?>" id="recipients_email" type="text" class="span12 required-entry validate-email" />
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
    <div class="form-actions">
        <button type="submit" class="pull-left btn btn-success btn-large<?php if (!$this->canSend()): ?> disabled<?php endif ?>"<?php if (!$this->canSend()): ?> disabled="disabled"<?php endif ?>><?php echo $this->__('Send email') ?></button>
        <div id="max_recipient_message" style="display:none;">
            <?php if ($this->getMaxRecipients()): ?>
                <p class="pull-right limit"><?php echo $this->__('Maximum %d email addresses allowed.', $this->getMaxRecipients()) ?></p>
            <?php endif; ?>
        </div>
        <?php if (1 < $this->getMaxRecipients()): ?>
            <p id="add_recipient_button" class="pull-right">
                <button type="button" onclick="add_recipient();" class="btn btn-large"><?php echo $this->__('Add recipient') ?></button>
            </p>
        <?php endif; ?>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var productSendtofriendForm = new VarienForm('product_sendtofriend_form');
    productSendtofriendForm.submit = function() {
        if(this.validator.validate()) {
            this.form.submit();
        }
    }.bind(productSendtofriendForm);
    //]]>
</script>
