<script>
    function decorateGenericActive(elements, decorateParams)
    {
        var allSupportedParams = ['odd', 'even', 'first', 'last', 'active'];
        var _decorateParams = {};
        var total = elements.length;

        if (total) {
            // determine params called
            if (typeof(decorateParams) == 'undefined') {
                decorateParams = allSupportedParams;
            }
            if (!decorateParams.length) {
                return;
            }
            for (var k in allSupportedParams) {
                _decorateParams[allSupportedParams[k]] = false;
            }
            for (var k in decorateParams) {
                _decorateParams[decorateParams[k]] = true;
            }

            // decorate elements
            // elements[0].addClassName('first'); // will cause bug in IE (#5587)
            if (_decorateParams.active) {
                Element.addClassName(elements[0], 'active');
            }
            if (_decorateParams.first) {
                Element.addClassName(elements[0], 'first');
            }
            if (_decorateParams.last) {
                Element.addClassName(elements[total-1], 'last');
            }
            for (var i = 0; i < total; i++) {
                if ((i + 1) % 2 == 0) {
                    if (_decorateParams.even) {
                        Element.addClassName(elements[i], 'even');
                    }
                }
                else {
                    if (_decorateParams.odd) {
                        Element.addClassName(elements[i], 'odd');
                    }
                }
            }
        }
    }
    
</script>
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <div class="block block-wishlist well">
        <div class="block-title">
            <h3><?php echo $this->__('Wishlist <small>(%d)</small>', $this->getItemCount()) ?></h3>
        </div>
        <div class="block-content">
            <?php if ($this->hasWishlistItems()): ?>
                <div class="" id="wishlist-sidebar">
                    <div class="">
                        <div id="wishlistCarousel" class="carousel slide">
                            <div class="carousel-inner">
                                <?php foreach ($this->getWishlistItems() as $_item): ?>
                                    <?php $product = $_item->getProduct(); ?>
                                    <div class="modal hide fade" id="<?php echo $this->escapeHtml($product->getId()) ?>" style="display: none;">
                                        <div class="modal-header">
                                            <a class="close" data-dismiss="modal">×</a>
                                            <h3><?php echo $this->__('Remove item') ?></h3>
                                        </div>
                                        <div class="modal-body">
                                            <p><?php echo $this->__('Are you sure you would like to remove this item from the wishlist?') ?></p>
                                            <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(300); ?>" width="300" height="300" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
                                        </div>
                                        <div class="modal-footer">
                                            <a href="<?php echo $this->getItemRemoveUrl($_item) ?>" class="btn btn-success"><?php echo $this->__('Remove this item') ?></a>
                                            <a href="#" class="btn" data-dismiss="modal"><?php echo $this->__('Cancel') ?></a>
                                        </div>
                                    </div>
                                    <dl class="item">
                                        <a class="product-image" href="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>">
                                            <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(250); ?>" width="250" height="250" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
                                        </a>
                                        <div class="carousel-caption">
                                            <div class="row-fluid">
                                                <div class="span6">
                                                    <?php if ($product->isSaleable() && $product->isVisibleInSiteVisibility()): ?>
                                                        <a href="<?php echo $this->getItemAddToCartUrl($_item) ?>" class="btn btn-success btn-mini"><?php echo $this->__('Add to cart') ?></a>
                                                    <?php endif; ?>
                                                </div>
                                                <div class="span4">
                                                    <strong><?php echo $this->getPriceHtml($product, false, '-wishlist') ?></strong>
                                                </div>
                                                <div class="span2">
                                                    <a class="pull-right" data-toggle="modal" href="#<?php echo $this->escapeHtml($product->getId()) ?>" title="<?php echo $this->__('Remove this item') ?>" ><span class="icon-remove"></span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </dl>
                                <?php endforeach; ?>
                            </div>
                            <a class="carousel-control left" href="#wishlistCarousel" data-slide="prev">‹</a>
                            <a class="carousel-control right" href="#wishlistCarousel" data-slide="next">›</a>
                        </div>
                        <script type="text/javascript">decorateGenericActive($$('#wishlistCarousel dl'), ['active']);</script>
                    </div>
                </div>
                <div class="actions">
                    <a class="btn btn-success" href="<?php echo $this->helper('wishlist')->getListUrl() ?>"><?php echo $this->__('Go to wishlist') ?></a>
                </div>
            <?php else: ?>
                <p class="empty"><?php echo $this->__('You have no items in your wishlist.') ?></p>
            <?php endif ?>
        </div>
    </div>
<?php endif ?>
