<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <?php if ($this->helper('wishlist')->isRssAllow() && $this->hasWishlistItems()): ?>
        <a href="<?php echo $this->helper('wishlist')->getRssUrl(); ?>" class="btn"><i class="fa-icon-rss"></i> <?php echo $this->__('RSS feed') ?></a>
        <hr class="clean"/>
    <?php endif; ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php if ($this->hasWishlistItems()): ?>
        <form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
            <fieldset>
                <?php echo $this->getBlockHtml('formkey') ?>
                <table class="table table-striped table-bordered table-condensed table-white" id="wishlist-table">
                    <thead>
                        <tr>
                            <th><?php echo $this->__('Product') ?></th>
                            <th><?php echo $this->__('Comment') ?></th>
                            <th><span class="nobr"><?php echo $this->__('Added on') ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('Add to cart') ?></span></th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->getWishlistItems() as $item): ?>
                            <?php
                            $product = $item->getProduct();
                            $isVisibleProduct = $product->isVisibleInSiteVisibility();
                            ?>
                            <tr>
                                <td>
                                    <a class="product-image" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(113, 113); ?>" width="113" height="113" alt="<?php echo $this->escapeHtml($product->getName()) ?>" /></a>
                                    <h2 class="product-name"><a href="<?php echo $this->getProductUrl($item) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></h2>
                                    <?php echo $this->getPriceHtml($product) ?>
                                    <?php echo $this->getDetailsHtml($item) ?>
                                </td>
                                <td>
                                    <textarea name="description[<?php echo $item->getWishlistItemId() ?>]" rows="3" cols="5" onfocus="focusComment(this)" onblur="focusComment(this)" title="<?php echo $this->__('Comment') ?>"><?php echo $this->getCommentValue($item); ?></textarea>
                                </td>
                                <td>
                                    <span class="nobr"><?php echo $this->getFormatedDate($item->getAddedAt()) ?></span>
                                </td>
                                <td>
                                    <?php if ($item->canHaveQty() && $isVisibleProduct): ?>
                                        <p><input type="text" class="qty" name="qty[<?php echo $item->getId() ?>]" value="<?php echo $this->getAddToCartQty($item) * 1 ?>" /></p>
                                    <?php endif; ?>
                                    <?php if ($product->isSaleable()): ?>
                                        <?php if ($isVisibleProduct): ?>
                                            <button type="button" title="<?php echo $this->__('Add to cart') ?>" onclick="addWItemToCart(<?php echo $item->getId(); ?>)" class="btn"><?php echo $this->__('Add to cart') ?></button>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                    <?php if ($isVisibleProduct): ?>
                                        <p><a href="<?php echo $this->getItemConfigureUrl($item) ?>"><?php echo $this->__('Edit') ?></a></p>
                                    <?php endif ?>
                                </td>
                                <td>
                                    <a href="<?php echo $this->getItemRemoveUrl($item) ?>" title="<?php echo $this->__('Remove item') ?>" onclick="return confirmRemoveWishlistItem();" class=""><i class="icon-trash"></i></a>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
                <script type="text/javascript">decorateTable('wishlist-table')</script>
                <div class="form-actions">
                    <button type="submit" onclick="this.name='save_and_share'" title="<?php echo $this->__('Share wishlist') ?>" class="btn btn-large"><?php echo $this->__('Share wishlist') ?></button>
                    <?php if ($this->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add all to cart') ?>" onclick="addAllWItemsToCart()" class="btn btn-large"><?php echo $this->__('Add all to cart') ?></button>
                    <?php endif; ?>
                    <button type="submit" title="<?php echo $this->__('Update wishlist') ?>" onclick="this.name='do'" class="btn btn-large btn-success"><?php echo $this->__('Update wishlist') ?></button>
                </div>
            </fieldset>
        </form>
    <?php else: ?>
        <p><?php echo $this->__('You have no items in your wishlist.') ?></p>
    <?php endif ?>
    <script type="text/javascript">
        //<![CDATA[
        function confirmRemoveWishlistItem() {
            return confirm('<?php echo $this->__('Are you sure you want to remove this product from your wishlist?') ?>');
        }

        function focusComment(obj) {
            if( obj.value == '<?php echo $this->helper('wishlist')->defaultCommentString() ?>' ) {
                obj.value = '';
            } else if( obj.value == '' ) {
                obj.value = '<?php echo $this->helper('wishlist')->defaultCommentString() ?>';
            }
        }

        function addWItemToCart(itemId) {
            var url = '<?php echo $this->getItemAddToCartUrl('%item%') ?>';
            url = url.gsub('%item%', itemId);
            var form = $('wishlist-view-form');
            if (form) {
                var input = form['qty[' + itemId + ']'];
                if (input) {
                    var separator = (url.indexOf('?') >= 0) ? '&' : '?';
                    url += separator + input.name + '=' + encodeURIComponent(input.value);
                }
            }
            setLocation(url);
        }

        function addAllWItemsToCart() {
            var url = '<?php echo $this->getUrl('*/*/allcart') ?>';
            var separator = (url.indexOf('?') >= 0) ? '&' : '?';
            $$('#wishlist-view-form .qty').each(
                function (input, index) {
                    url += separator + input.name + '=' + encodeURIComponent(input.value);
                    separator = '&';
                }
            );

            setLocation(url);
        }
        //]]>
    </script>
    <?php

 endif ?>
