<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
/* @var $this Mage_Catalog_Block_Product_List_Toolbar */
?>

<?php if ($this->getCollection()->getSize()): ?>
    <div class="row-fluid">
        <div class="btn-toolbar thumbnail">
            <div class="btn-group pull-right">
                <?php if ($this->isEnabledViewSwitcher()): ?>
                    <?php $_modes = $this->getModes(); ?>
                    <?php if ($_modes && count($_modes) > 1): ?>
                        <?php foreach ($this->getModes() as $_code => $_label): ?>
                            <?php $icon = $_code ?>
                            <?php if ('grid' === $_code) : ?>
                                <?php $icon = 'th-large' ?>
                            <?php endif ?>
                            <?php if ($this->isModeActive($_code)): ?>
                                <a href="#" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?> btn btn-inverse active"><span class="icon-<?php echo strtolower($icon); ?> icon-white"></span></a>
                            <?php else: ?>
                                <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?> btn"><span class="icon-<?php echo strtolower($_code); ?>"></span></a>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
            <div class="btn-group">
                <button class="btn"><?php echo $this->__('Show') ?></button>
                <button class="btn dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
                <ul class="dropdown-menu" onchange="setLocation(this.value)">
                    <?php foreach ($this->getAvailableLimit() as $_key => $_limit): ?>
                        <li <?php if ($this->isLimitCurrent($_key)): ?> class="active" <?php endif ?>>
                            <a href="<?php echo $this->getLimitUrl($_key) ?>"><?php echo $_limit ?> <?php echo $this->__('per page') ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php foreach ($this->getAvailableOrders() as $_key => $_order): ?>
                <div class="btn-group">
                    <a class="btn <?php if ($this->isOrderCurrent($_key)): ?>btn-success disabled<?php endif; ?>" href="<?php echo $this->getOrderUrl($_key, 'asc') ?>"><?php echo $this->__($_order) ?></a>
                </div>
            <?php endforeach; ?>
            <div class="btn-group">
                <?php if ($this->getCurrentDirection() == 'desc'): ?>
                    <a class="btn" href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set ascending direction') ?>">
                        <span class="icon-arrow-down"></span>
                    </a>
                <?php else: ?>
                    <a class="btn" href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set descending direction') ?>">
                        <span class="icon-arrow-up"></span>
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif ?>
