<form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" name="guest_post">
    <fieldset>
        <div class="control-group">
            <label for="oar_order_id" class="control-label required"><?php echo Mage::helper('sales')->__('Order ID') ?></label>
            <div class="controls">
                <input type="text" class="input-text required-entry span3" id="oar_order_id" name="oar_order_id" />
            </div>
        </div>
        <hr/>
        <p><?php echo Mage::helper('sales')->__('Enter the last name and email address (or post/ZIP code) that was given in the order\'s billing address.') ?>.</p>
        <div class="control-group">
            <label for="oar_billing_lastname" class="control-label required"><?php echo Mage::helper('sales')->__('Billing last name') ?></label>
            <div class="controls">
                <input type="text" class="input-text required-entry span3" id="oar_billing_lastname" name="oar_billing_lastname" />
            </div>
        </div>

        <div class="control-group">
            <label class="control-label"><?php echo Mage::helper('sales')->__('Find order by') ?></label>
            <div class="controls">
                <select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
                    <option value="email">Email address</option>
                    <option value="zip">Post/ZIP code</option>
                </select>
            </div>
        </div>

        <div class="control-group" id="oar-email" style="clear:both;">
            <label for="oar_email" class="control-label required"><?php echo Mage::helper('sales')->__('Email address') ?></label>
            <div class="controls">
                <input type="text" class="input-text validate-email required-entry span3" id="oar_email" name="oar_email" >
            </div>
        </div>
        <div class="control-group" id="oar-zip" style="display:none;clear:both;">
            <label for="oar_zip" class="control-label required"><?php echo Mage::helper('sales')->__('Post/ZIP code') ?></label>
            <div class="controls">
                <input type="text" class="input-text required-entry span3" id="oar_zip" name="oar_zip" />
            </div>
        </div>

        <div class="form-actions">
            <button type="submit" title="Continue" class="btn btn-large"><?php echo Mage::helper('sales')->__('Continue') ?></button>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
    //<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
        $('oar-zip').hide();
        $('oar-email').show();
    }

    var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

    function showIdentifyBlock(id)
    {
        if (id == 'zip') {
            $('oar-zip').show();
            $('oar-email').hide();
        } else if (id == 'email') {
            $('oar-zip').hide();
            $('oar-email').show();
        }
        return false;
    }
    //]]>
</script>
