<?php if ($this->getMessagesBlock()->getMessageCollection()->count()): ?>
    <?php foreach ($this->getMessagesBlock()->getMessageCollection()->getItems() as $message): ?>
        <div class="alert alert-<?php echo $message->getType() ?> fade in">
            <a class="close" data-dismiss="alert">×</a>
            <?php echo $message->getCode() ?>
        </div>
    <?php endforeach; ?>
    <?php $this->getMessagesBlock()->getMessageCollection()->clear(); ?>
<?php endif; ?>
