<?php $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('buttons') ?>
<hr/>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<?php $_links = $this->getLinks(); ?>
<ul class="nav nav-tabs">
    <?php foreach ($_links as $_link): ?>
        <?php if($_link->getUrl()): ?>
            <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
        <?php else: ?>
            <li class="active"><a href="#"><?php echo $_link->getLabel() ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<p class="order-date"><?php echo $this->__('Order date: <code>%s</code>', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
<div class="row-fluid">
    <div class="span6 well">
        <h3><?php echo $this->__('Shipping address') ?></h3>
        <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
    </div>
    <div class="span6 well">
        <h3><?php echo $this->__('Shipping method') ?><?php /* | <a href="#"><?php echo $this->__('Track Order') ?></a>*/ ?></h3>
        <?php if ($_order->getShippingDescription()): ?>
            <?php echo $_order->getShippingDescription() ?>
        <?php else: ?>
            <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<div class="row-fluid">
    <div class="span6 well">
        <h3><?php echo $this->__('Billing address') ?></h3>
        <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
    </div>
    <div class="span6 well">
        <h3><?php echo $this->__('Payment method') ?></h3>
        <?php echo $this->getPaymentInfoHtml() ?>
    </div>
</div>
