<?php $_orders = $this->getOrders(); ?>
<div>
    <?php if (sizeof($_orders->getItems()) > 0): ?>
        <p class="pull-right"><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('View all') ?></a></p>
    <?php endif; ?>
    <h2><?php echo $this->__('Recent orders') ?></h2>
</div>
<?php if (sizeof($_orders->getItems()) > 0): ?>
    <table class="my-orders-table table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th><?php echo $this->__('Order #') ?></th>
                <th><?php echo $this->__('Date') ?></th>
                <th><?php echo $this->__('Ship to') ?></th>
                <th><span class="nobr"><?php echo $this->__('Order total') ?></span></th>
                <th><?php echo $this->__('Status') ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_orders as $_order): ?>
            <tr>
                <td><?php echo $_order->getRealOrderId() ?></td>
                <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                <td><em><?php echo $_order->getStatusLabel() ?></em></td>
                <td class="a-center">
                    <span class="nobr">
                        <a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View order') ?></a>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                        <?php endif ?>
                    </span>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
