<?php
/**
 * Last order sidebar
 *
 * @see Mage_Sale_Block_Reorder_Sidebar
 */
?>
<?php $_items = $this->getItems() ?>
<?php if ($_items): ?>
    <div class="block block-reorder well">
        <div class="block-title">
            <h3><?php echo $this->__('Orders') ?></h3>
        </div>
        <form method="post" action="<?php echo $this->getFormActionUrl() ?>" id="reorder-validate-detail">
            <div class="block-content">
                <p class="block-subtitle"><?php echo $this->__('Last ordered items:') ?></p>
                <?php $_showAddButtonFlag = false ?>
                <?php foreach ($_items as $_item): ?>
                    <div class="controls">
                        <?php if ($this->isItemAvailableForReorder($_item)): ?>
                            <?php $_showAddButtonFlag = true ?>
                            <label class="checkbox">
                                <input type="checkbox" name="order_items[]" id="reorder-item-<?php echo $_item->getId() ?>" value="<?php echo $_item->getId() ?>" title="<?php echo $this->__('Add to cart') ?>" class="checkbox validate-one-required-by-name" />
                                <a href="<?php echo $_item->getProduct()->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                            </label>
                            <script type="text/javascript">
                                //<![CDATA[
                                $('reorder-item-<?php echo $_item->getId() ?>').advaiceContainer = 'cart-sidebar-reorder-advice-container';
                                //]]>
                            </script>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
                <script type="text/javascript">decorateList('cart-sidebar-reorder')</script>
                <div id="cart-sidebar-reorder-advice-container"></div>
                <div class="actions">
                    <?php if ($_showAddButtonFlag): ?>
                        <button type="submit" title="<?php echo $this->__('Add to cart') ?>" class="btn btn-success"><?php echo $this->__('Add to cart') ?></button>
                    <?php endif; ?>
                    <a class="btn" href="<?php echo $this->getUrl('customer/account') ?>"><?php echo $this->__('View all'); ?></a>
                </div>
            </div>
        </form>
    </div>
    <?php echo $this->getPagerHtml(); ?>
    <script type="text/javascript">
        //<![CDATA[
        var reorderFormDetail = new VarienForm('reorder-validate-detail');
        //]]>
    </script>
    <?php
 endif ?>
