<div id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div class="control-group">
        <label for="po_number" class="control-label required"><?php echo $this->__('Purchase order number') ?></label>
        <div class="controls">
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo $this->__('Purchase order number') ?>" class="required-entry" value="<?php echo $this->htmlEscape($this->getInfoData('po_number')) ?>" />
        </div>
    </div>
</div>
